version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.15.4 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory

      # https://circleci.com/docs/2.0/caching/#yarn-node
      # using progressively more generic keys to increase hit odds
      - restore_cache: 
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
      - run:
          name: Install packages
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: yarn test
      - run:
          name: Run coverage
          command: yarn coverage