version: 2.1
jobs:
  build:
    parallelism: 2
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache: # using progressively more generic keys to increase hit odds
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
      - run:
          name: Install packages
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Split tests
          command: |
            TEST_FILES=$(circleci tests glob "src/**/*.test.ts" | circleci tests split --split-by=timings)
            echo 'export TEST_FILES_ENV="TEST_FILES"' >> $BASH_ENV
      - run:
          name: Run tests
          command: |
            echo "Running test cases in: $TEST_FILES_ENV"
            yarn test $TEST_FILES_ENV
      - run: # https://github.com/michaelleeallen/mocha-junit-reporter/issues/132#issuecomment-864212687
          name: Process test report
          when: always
          command: |
            # Convert absolute paths to relative to support splitting tests by timing
            if [ -e test-results.xml ]; then
              sed -i "s|`pwd`/||g" test-results.xml
            fi            
      - store_test_results:
          path: test-results.xml
      - run:
          name: Run coverage
          command: |
            echo "Running coverage in: $TEST_FILES_ENV"
            yarn coverage $TEST_FILES_ENV
      - store_artifacts:
          path: coverage