version: 2.1
jobs:
  build:
    parallelism: 2
    docker:
      - image: cimg/node:14.15.4
    steps:
      - checkout
      - restore_cache: # using progressively more generic keys to increase hit odds
          keys:
            - yarn-packages-v1-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-
      - run:
          name: Install packages
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-v1-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: |
            set -e
            TEST_FILES=$(circleci tests glob "src/**/*.test.ts" | circleci tests split --split-by=timings)
            echo "Running test cases in: $TEST_FILES"
            node_modules/ts-mocha/bin/ts-mocha $TEST_FILES --reporter mocha-junit-reporter
      - store_test_results:
          path: test-results.xml
      - run:
          name: Run coverage
          command: yarn coverage
      - store_artifacts:
          path: coverage